# Generated by Django 2.2.6 on 2019-11-20 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='sex',
        ),
    ]
