# Generated by Django 2.2.6 on 2019-11-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_remove_comment_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='backcall',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
