# Generated by Django 2.2.6 on 2019-11-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_backcall_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='backcall',
            name='message',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='comment',
            name='published',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
