# Generated by Django 2.2.6 on 2019-11-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20191121_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
