# Generated by Django 2.2.6 on 2019-12-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20191214_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='files',
        ),
    ]
