# Generated by Django 2.2.6 on 2019-12-21 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_comment_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='category',
        ),
    ]
