# Generated by Django 2.2.6 on 2019-12-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_auto_20191221_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backcall',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
