# Generated by Django 2.2.6 on 2019-12-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_auto_20191221_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backcall',
            name='datetime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
